#!/usr/bin/env node
/**
 * Turn a model's translated JSON into a dictionary the app can use.
 *
 *   node scripts/translation-import.mjs si answer-part1.txt answer-part2.txt
 *
 * The files are the replies to the prompts from translation-prompt.mjs. Each
 * is expected to be a JSON object, but a reply wrapped in code fences or
 * prose is tolerated: the first "{" to the last "}" is what gets parsed.
 *
 * The result is checked against en.ts before anything is written: every key
 * must exist in English, every placeholder in the English must appear in the
 * translation, and any English key with no translation is listed so it can
 * be asked for. The dictionary is written to lib/i18n/<code>.ts.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const [code, ...files] = process.argv.slice(2);
if (!code || files.length === 0) {
  console.error('Usage: node scripts/translation-import.mjs <code, e.g. si> <reply.json> [more replies...]');
  process.exit(1);
}

const source = readFileSync(join(here, '..', 'lib', 'i18n', 'en.ts'), 'utf8');
const body = source.slice(source.indexOf('export const en = {'));
const entry = /^\s+'([A-Za-z0-9_.]+)':\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")\s*,/gm;
const english = new Map();
for (const m of body.matchAll(entry)) {
  english.set(m[1], (m[2] ?? m[3]).replace(/\\'/g, "'").replace(/\\"/g, '"'));
}

const placeholders = (s) => [...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort();

const merged = new Map();
const problems = [];
for (const file of files) {
  const raw = readFileSync(file, 'utf8');
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  if (start < 0 || end < start) {
    problems.push(`${file}: no JSON object found`);
    continue;
  }
  let parsed;
  try {
    parsed = JSON.parse(raw.slice(start, end + 1));
  } catch (err) {
    problems.push(`${file}: JSON does not parse - ${err.message}`);
    continue;
  }
  for (const [key, value] of Object.entries(parsed)) {
    if (!english.has(key)) {
      problems.push(`${file}: unknown key ${key} (ignored)`);
      continue;
    }
    if (typeof value !== 'string' || !value.trim()) {
      problems.push(`${file}: ${key} is empty (ignored)`);
      continue;
    }
    const want = placeholders(english.get(key));
    const got = placeholders(value);
    if (want.join(',') !== got.join(',')) {
      problems.push(`${key}: placeholders differ - English has {${want.join('} {')}}, translation has {${got.join('} {')}}`);
    }
    merged.set(key, value.trim());
  }
}

const missing = [...english.keys()].filter((k) => !merged.has(k));

const q = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const lines = [
  "import type { MessageKey } from './en';",
  '',
  '/**',
  ` * ${code}: ${merged.size} of ${english.size} strings. Any key missing here shows its`,
  ' * English text, so a partial dictionary is safe to ship.',
  ' *',
  ' * Generated by scripts/translation-import.mjs - edit by hand freely, but',
  ' * keep every {placeholder} the English string has.',
  ' */',
  `export const ${code}: Partial<Record<MessageKey, string>> = {`,
];
for (const key of english.keys()) {
  if (merged.has(key)) lines.push(`  ${q(key)}: ${q(merged.get(key))},`);
}
lines.push('};', '');

const out = join(here, '..', 'lib', 'i18n', `${code}.ts`);
writeFileSync(out, lines.join('\n'));

console.log(`${merged.size} of ${english.size} strings -> ${out}`);
if (missing.length) {
  console.log(`\n${missing.length} still English (ask for these next):`);
  for (const k of missing) console.log('  ' + k + '  =  ' + JSON.stringify(english.get(k)));
}
if (problems.length) {
  console.log(`\n${problems.length} things to look at:`);
  for (const p of problems) console.log('  ' + p);
}
